Move parsed_coin to cosmos and change parsing approach
fpco/cosmos-rs pull request #33
Opened 2024-06-27 18:07 UTC by ribeirotomas1904

2024-06-28 03:21 UTC, snoyberg requested changes

2024-06-28 03:21 UTC, snoyberg commented on packages/cosmos/src/parsed_coin.rs
> +            if s.is_empty() {
I know I commented to move away from `anyhow`. But just mentioning a trick here is to use `ensure`:

```rust
anyhow::ensure!(!s.is_empty(), "Input is empty");
```

2024-06-28 03:21 UTC, snoyberg commented on packages/cosmos/src/parsed_coin.rs
> +                    let amount = &s[..denom_first_index];
Also possible: [`split_at`](https://doc.rust-lang.org/stable/std/primitive.str.html#method.split_at).

2024-06-28 03:21 UTC, snoyberg commented on packages/cosmos/Cargo.toml
> +anyhow = { version = "1.0.86", features = ["backtrace"] }
Within the cosmos lib, we always want to use well-structured error messages using thiserror. Please see the error.rs module.

2024-06-28 11:45 UTC, ribeirotomas1904 commented on packages/cosmos/src/parsed_coin.rs
> +            if s.is_empty() {
very handy!

2024-06-28 11:46 UTC, ribeirotomas1904 commented on packages/cosmos/src/parsed_coin.rs
> +                    let amount = &s[..denom_first_index];
ohhhh, that's exactly what i needed

2024-06-28 11:47 UTC, ribeirotomas1904 commented on packages/cosmos/Cargo.toml
> +anyhow = { version = "1.0.86", features = ["backtrace"] }
ack

2024-06-30 05:29 UTC, snoyberg approved these changes

2024-06-30 05:29 UTC, merged