Generate signing keys from cosmos-rs
fpco/cosmos-rs pull request #50
Opened 2024-11-20 19:40 UTC by rgomezr391

Hello team,

I'd like to get some early feedback on this, this PR is to add a new feature to generate signing keys from cosmos-rs.

Please refer to Jira issue for information on the requirements: https://credencecapital.atlassian.net/browse/BLZ-281

I'm new to cosmos-rs space so please feel free to add whatever feedback you consider relevant for me to learn. Also, I added this new functionality on the cosmos-rs library, not sure if some of this functionality must be exposed through the CLI, if that's the case please let me know and I can do it.

2024-11-21 03:04 UTC, snoyberg reviewed
The existing `Wallet` struct has a `privkey` field which contains a `SecretKey`. Instead of adding new data types, what about exposing a method on `Wallet` for returning the secret key? Then we can leverage the existing code paths for generating wallets.

2024-11-21 03:23 UTC, psibi commented
I think the Wallet type already has some mechanism to sign, although not sure that's what you want.

2024-11-21 05:03 UTC, rgomezr391 commented
> The existing `Wallet` struct has a `privkey` field which contains a `SecretKey`. Instead of adding new data types, what about exposing a method on `Wallet` for returning the secret key? Then we can leverage the existing code paths for generating wallets.

@snoyberg I think that's totally doable, however, by reading the Jira issue description I'm not sure that's the way Konstantinos is expecting to use the generation of the signing keys... As far as I understand, we need to replicate the existing capability of cosmos sdk in golang for generating private keys (see [this](https://github.com/cosmos/cosmos-sdk/blob/main/crypto/keys/secp256k1/secp256k1.go#L91C6-L91C16))

I can clarify with him if this works, if that's the case then we can just update the existing Wallet module instead of creating a dedicated Crypto module.

2024-11-21 05:04 UTC, rgomezr391 commented
> I think the Wallet type already has some mechanism to sign, although not sure that's what you want.

yeah @psibi, you're totally right, the dependency already existed, I just removed the new dependency and used the existing one, thanks for your feedback.

2024-11-22 06:42 UTC, snoyberg approved these changes
I'm OK with this approach, though I'm surprised that it wasn't based on `Wallet` from previous discussion. Approving to avoid blocking, merge when you're ready.

2024-11-22 06:42 UTC, snoyberg commented on packages/cosmos-bin/src/crypto.rs
> +    GenK256KeyPair {},
This might be a mouthful to type :)

2024-11-22 13:47 UTC, rgomezr391 commented on packages/cosmos-bin/src/crypto.rs
> +    GenK256KeyPair {},
I removed the K256 to make it shorter and easier to type

2024-11-22 14:38 UTC, psibi commented on packages/cosmos/src/wallet.rs
> +    pub fn gen_priv_key() -> Xpriv {
Since this is part of `impl Wallet`, probably this should take `&self` as parameter and return `self.privkey` instead ?

2024-11-23 02:38 UTC, psibi approved these changes
What I meant to say was that the command, `cosmos wallet gen-wallet` already has mechanism for generating a wallet. You can add an option there `--only-keys` to print the things that you require for your use case.

That being said, I don't want to block this PR on this.

2024-11-24 08:21 UTC, snoyberg commented on packages/cosmos/src/wallet.rs
> +    pub fn gen_priv_key() -> Xpriv {
What I was trying to avoid with my previous comments was the duplicated key generation code. We already have `Wallet::generate`, that's what I'd meant by reusing the functionality in `Wallet`.

2024-11-25 07:50 UTC, snoyberg requested changes

2024-11-25 07:50 UTC, snoyberg commented on packages/cosmos-bin/src/wallet.rs
> +        Subcommand::GenKeyPair {} => gen_key_pair()?,
Instead of a separate CLI command, what about including this with GenWallet? GenWallet can simply spit out the public/private keys as well.

2024-11-25 07:50 UTC, snoyberg commented on packages/cosmos/src/wallet.rs
> +    pub fn gen_public_key(xpriv: Xpriv) -> PublicKey {
It's confusing to call this `gen_` when it's not generating anything. Regardless, for both this and `gen_priv_key`, please change them to be accessor methods on a `&Wallet`, e.g. `fn get_public_key(&self) -> PublicKey` (or maybe `&PublicKey`, depends on the types).

2024-11-25 07:50 UTC, snoyberg commented on packages/cosmos-bin/src/wallet.rs
> +    let private_key_hex = hex::encode(privkey.private_key.secret_bytes()).to_uppercase();
Looks like [`display_secret`](https://docs.rs/secp256k1/0.29.0/secp256k1/struct.SecretKey.html#method.display_secret) will handle this conversion too without needing to reach for `hex`.

2024-11-25 07:50 UTC, snoyberg commented on packages/cosmos-bin/src/wallet.rs
> +    let public_key_hex = hex::encode(public_key.serialize()).to_uppercase();
And it looks like there's a `Display` impl for public keys already.

2024-11-25 17:43 UTC, snoyberg approved these changes

2024-11-25 17:43 UTC, snoyberg commented on packages/cosmos-bin/src/main.rs
> +        public_key.push_str(&format!("{:02x}", byte));
As mentioned on Slack: I thought there was a `Display` impl for this type that handled the hex encoding. If not: apologies, I didn't mean to make you reimplement hex encoding. If so, do you mind switching over to it?

LGTM, so approving.

2024-11-25 19:42 UTC, merged