feat: transaction search by events
fpco/cosmos-rs pull request #54
Opened 2024-12-13 11:03 UTC by scorpioborn

## Description

The following PR adds search functionality based on the event list.

2024-12-15 08:36 UTC, snoyberg requested changes

2024-12-15 08:36 UTC, snoyberg commented on packages/cosmos/src/client.rs
> +                        sequence,
Looks like these are unnecessary changes and are breaking the formatting checks in CI.

2024-12-15 08:36 UTC, snoyberg commented on packages/cosmos/src/client.rs
> +            query: query.unwrap_or("".into()),
What would it mean to receive no query? It seems like we shouldn't have a default value here, and instead turn the parameter into a `String`.

2024-12-15 08:36 UTC, snoyberg commented on packages/cosmos/src/client.rs
> +        events: &Vec<String>,
NIT: generally we don't pass in references to Vecs, but rather references to slices: `&[String]`. Then, instead of `.clone()`, you could use `.to_owned()` below. An alternative is something like:

```rust
events: impl Into<Vec<String>>
```

This allows for a little bit more efficiency in some cases by bypassing an unneeded allocation.

2024-12-15 08:36 UTC, snoyberg commented on packages/cosmos/src/client.rs
> +                    .map(|x| x)
This is a no-op and can be removed.

2024-12-16 11:52 UTC, scorpioborn commented
Closed according to the discussion, the feature is not needed anymore

2024-12-16 11:52 UTC, closed without merging